### ISSUE TITLE
bash 可以直接实现该功能

### ISSUE THREAD

**Issue by wangtuanjie** [ma6174/ioe#1]
如下两者都可以：
1. `tee /dev/fd/2`
2. `tee >(cat 1>&2)`

**Comment by ma6174** [comment]
:+1: 

之前没想起来用bash如何实现，就直接用go写了一个。

bash重定向用法挺多的，网上看到一个文档，后面学习一下

https://github.com/pkrumins/bash-redirections-cheat-sheet

![](https://raw.githubusercontent.com/pkrumins/bash-redirections-cheat-sheet/master/bash-redirections-cheat-sheet.png)
